import CryptoKit
import Foundation
import Testing
@testable import MindBudget

@Suite(.serialized)
struct PublicConfigurationTransportTests {
    private static let runsLiveDevelopmentWorkerTest =
        ProcessInfo.processInfo.environment["MINDBUDGET_LIVE_PUBLIC_CONFIG_TESTS"] == "1"

    @Test
    func productionSignerGoldenResponseVerifiesWithTheEmbeddedProductionKey() throws {
        // Generated by the independent signer from the repository-external production private
        // key. This is deliberately not produced by the client test fixture encoder.
        let envelope = #"{"algorithm":"Ed25519","keyID":"mb-config-2026-01","payloadBase64":"eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOmZhbHNlfSwic2NoZW1hVmVyc2lvbiI6MX0=","signatureBase64":"LPfUflHQXtEoRWBDXm2KZH2KL0eEUaQQiZW8wn+vI/Lx7Z/5w1RcqvIBRNN7GDO3nr2iVk9tZ4ne6qDbmBw1Dg=="}"#
        let now = try #require(PublicConfigurationTimestamp.date(from: "2026-08-15T03:00:00Z"))
        let verified = try PublicConfigurationVerifier(
            policy: PublicConfigurationProductionTrust.verificationPolicy
        ).verify(envelopeData: Data(envelope.utf8), now: now)

        #expect(verified.payload.configVersion == 1)
        #expect(verified.payload.issuedAt == PublicConfigurationTimestamp.date(from: "2026-08-15T02:00:00Z"))
        #expect(verified.payload.expiresAt == PublicConfigurationTimestamp.date(from: "2026-08-22T02:00:00Z"))
        #expect(verified.payload.presentation.proValueTriggersEnabled == false)
    }

    @Test(.enabled(if: Self.runsLiveDevelopmentWorkerTest))
    func liveDevelopmentWorkerResponsePassesTheProductionTrustAndSchemaBoundary() async throws {
        let result = await FixedPublicConfigurationTransport(environment: .development).fetch(
            metadata: PublicConfigurationRequestMetadata(
                appVersion: "0.9.6",
                lastAcceptedConfigVersion: 1
            )
        )
        guard case let .envelope(data) = result else {
            Issue.record("The live Development Worker did not return an accepted envelope")
            return
        }
        let verified = try PublicConfigurationVerifier(
            policy: PublicConfigurationProductionTrust.verificationPolicy
        ).verify(envelopeData: data, now: Date())

        #expect(verified.payload.configVersion == 1)
        #expect(verified.payload.presentation.proValueTriggersEnabled)
    }

    @Test
    func exactEnvironmentRequestsContainOnlyReviewedMetadataAndNoBody() async throws {
        let expectedHosts: [PublicConfigurationDeploymentEnvironment: String] = [
            .development: "mindbudget-public-config-dev.yehao1105.workers.dev",
            .staging: "mindbudget-public-config-staging.yehao1105.workers.dev",
            .production: "mindbudget-public-config.yehao1105.workers.dev"
        ]

        for environment in PublicConfigurationDeploymentEnvironment.allCases {
            let loader = RecordingPublicConfigurationLoader(
                response: Self.response(url: environment.endpoint),
                data: Data("{}".utf8)
            )
            let transport = FixedPublicConfigurationTransport(
                environment: environment,
                loader: loader
            )

            let result = await transport.fetch(
                metadata: PublicConfigurationRequestMetadata(
                    appVersion: "0.9.6",
                    lastAcceptedConfigVersion: 42
                )
            )
            let request = try #require(await loader.capturedRequest())

            #expect(result == .envelope(Data("{}".utf8)))
            #expect(request.url?.scheme == "https")
            #expect(request.url?.host == expectedHosts[environment])
            #expect(request.url?.path == "/v1/config")
            #expect(request.url?.query == nil)
            #expect(request.httpMethod == "GET")
            #expect(request.httpBody == nil)
            #expect(request.value(forHTTPHeaderField: "Accept") == "application/json")
            #expect(
                request.value(forHTTPHeaderField: FixedPublicConfigurationTransport.appVersionHeader)
                    == "0.9.6"
            )
            #expect(
                request.value(forHTTPHeaderField: FixedPublicConfigurationTransport.configVersionHeader)
                    == "42"
            )
        }
    }

    @Test
    func invalidMetadataFailsBeforeAnyNetworkLoad() async {
        let loader = RecordingPublicConfigurationLoader(
            response: Self.response(url: PublicConfigurationDeploymentEnvironment.production.endpoint),
            data: Data("{}".utf8)
        )
        let transport = FixedPublicConfigurationTransport(
            environment: .production,
            loader: loader
        )

        let invalidVersions = ["", "0.9.6 user", String(repeating: "1", count: 33)]
        for version in invalidVersions {
            #expect(
                await transport.fetch(
                    metadata: PublicConfigurationRequestMetadata(
                        appVersion: version,
                        lastAcceptedConfigVersion: nil
                    )
                ) == PublicConfigurationFetchResult.failed(.invalidRequestMetadata)
            )
        }
        #expect(await loader.loadCount() == 0)
    }

    @Test
    func redirectWrongURLStatusTypeEmptyAndOversizeResponsesFailClosed() async {
        let endpoint = PublicConfigurationDeploymentEnvironment.production.endpoint
        let fixtures: [(HTTPURLResponse, Data, PublicConfigurationTransportFailureReason)] = [
            (Self.response(url: endpoint, status: 302), Data("{}".utf8), .redirectRejected),
            (
                Self.response(url: URL(string: "https://example.invalid/v1/config")!),
                Data("{}".utf8),
                .responseURLMismatch
            ),
            (Self.response(url: endpoint, status: 503), Data("{}".utf8), .invalidHTTPStatus),
            (
                Self.response(url: endpoint, contentType: "text/plain"),
                Data("{}".utf8),
                .invalidContentType
            ),
            (Self.response(url: endpoint), Data(), .emptyResponse),
            (
                Self.response(url: endpoint),
                Data(
                    repeating: 0,
                    count: PublicConfigurationVerificationPolicy.maximumEnvelopeBytes + 1
                ),
                .responseTooLarge
            )
        ]

        for (httpResponse, data, expectedReason) in fixtures {
            let transport = FixedPublicConfigurationTransport(
                environment: .production,
                loader: RecordingPublicConfigurationLoader(response: httpResponse, data: data)
            )
            #expect(
                await transport.fetch(
                    metadata: PublicConfigurationRequestMetadata(
                        appVersion: "0.9.6",
                        lastAcceptedConfigVersion: nil
                    )
                ) == .failed(expectedReason)
            )
        }
    }

    @Test
    func serviceAcceptsVerifiedRemoteAndLogsOnlyClosedReasonCodes() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let persistence = TransportConfigurationPersistence()
        let controller = PublicConfigurationController(
            verifier: fixture.verifier,
            persistence: persistence
        )
        let observer = RecordingPublicConfigurationObserver()
        let service = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(
                result: .envelope(try fixture.envelopeData(version: 3, enabled: true))
            ),
            observer: observer,
            appVersion: "0.9.6"
        )

        let resolution = await service.refresh(now: fixture.now)

        #expect(resolution.source == .remote)
        #expect(resolution.acceptedConfigVersion == 3)
        #expect(resolution.presentation.proValueTriggersEnabled)
        #expect(observer.resolutionReasons() == [.remoteAccepted])
        #expect(observer.transportReasons().isEmpty)
    }

    @Test
    func invalidSignatureAndOfflineTransportRetainOnlyVerifiedCache() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let persistence = TransportConfigurationPersistence()
        let controller = PublicConfigurationController(
            verifier: fixture.verifier,
            persistence: persistence
        )
        _ = await controller.acceptRemote(
            envelopeData: try fixture.envelopeData(version: 2, enabled: true),
            now: fixture.now
        )

        let invalidObserver = RecordingPublicConfigurationObserver()
        let invalidService = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(
                result: .envelope(try fixture.envelopeDataWithInvalidSignature())
            ),
            observer: invalidObserver,
            appVersion: "0.9.6"
        )
        let invalidResolution = await invalidService.refresh(now: fixture.now)
        #expect(invalidResolution.source == .verifiedCache)
        #expect(invalidResolution.presentation.proValueTriggersEnabled)
        #expect(invalidObserver.resolutionReasons() == [.rejectedSignature])

        let offlineObserver = RecordingPublicConfigurationObserver()
        let offlineService = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(result: .failed(.offline)),
            observer: offlineObserver,
            appVersion: "0.9.6"
        )
        let offlineResolution = await offlineService.refresh(now: fixture.now)
        #expect(offlineResolution.source == .verifiedCache)
        #expect(offlineResolution.presentation.proValueTriggersEnabled)
        #expect(offlineObserver.transportReasons() == [.offline])
        #expect(offlineObserver.resolutionReasons() == [.cacheAccepted])
    }

    @MainActor
    @Test
    func signedPresentationControlsOnlyTheOptionalFreeValueTrigger() async throws {
        let controller = try DataController(isStoredInMemoryOnly: true)
        let enabled = PublicConfigurationResolution(
            presentation: PublicConfigurationPresentation(proValueTriggersEnabled: true),
            source: .remote,
            acceptedConfigVersion: 1
        )
        let freeSession = AppSession(
            dataActor: controller.dataActor,
            publicConfigurationService: FixedPublicConfigurationService(resolution: enabled)
        )

        #expect(freeSession.offersAppleOnDeviceAIProValueTrigger == false)
        await freeSession.refreshPublicConfiguration(now: Date())
        #expect(freeSession.offersAppleOnDeviceAIProValueTrigger)

        #if DEBUG
        let proSession = AppSession(
            dataActor: controller.dataActor,
            featureAccessService: DebugFeatureAccessProvider(entitlements: .proSubscription),
            publicConfigurationService: FixedPublicConfigurationService(resolution: enabled)
        )
        await proSession.refreshPublicConfiguration(now: Date())
        #expect(proSession.existingPremiumEntryAccess.offersAppleOnDeviceAI)
        #expect(proSession.offersAppleOnDeviceAIProValueTrigger == false)
        #endif
    }

    private static func response(
        url: URL,
        status: Int = 200,
        contentType: String = "application/json; charset=utf-8"
    ) -> HTTPURLResponse {
        HTTPURLResponse(
            url: url,
            statusCode: status,
            httpVersion: "HTTP/1.1",
            headerFields: ["Content-Type": contentType]
        )!
    }
}

private actor RecordingPublicConfigurationLoader: PublicConfigurationHTTPLoading {
    private let response: HTTPURLResponse
    private let data: Data
    private var requests: [URLRequest] = []

    init(response: HTTPURLResponse, data: Data) {
        self.response = response
        self.data = data
    }

    func load(
        request: URLRequest,
        maximumResponseBytes: Int
    ) async throws -> PublicConfigurationHTTPResponse {
        _ = maximumResponseBytes
        requests.append(request)
        return PublicConfigurationHTTPResponse(data: data, response: response)
    }

    func capturedRequest() -> URLRequest? { requests.last }
    func loadCount() -> Int { requests.count }
}

private struct FixedResultPublicConfigurationTransport: PublicConfigurationFetching {
    let result: PublicConfigurationFetchResult

    func fetch(metadata: PublicConfigurationRequestMetadata) async -> PublicConfigurationFetchResult {
        _ = metadata
        return result
    }
}

private final class RecordingPublicConfigurationObserver: PublicConfigurationReasonObserving,
    @unchecked Sendable {
    private let lock = NSLock()
    private var transports: [PublicConfigurationTransportFailureReason] = []
    private var resolutions: [PublicConfigurationResolutionReason] = []

    func record(transport reason: PublicConfigurationTransportFailureReason) {
        lock.withLock { transports.append(reason) }
    }

    func record(resolution reason: PublicConfigurationResolutionReason) {
        lock.withLock { resolutions.append(reason) }
    }

    func transportReasons() -> [PublicConfigurationTransportFailureReason] {
        lock.withLock { transports }
    }

    func resolutionReasons() -> [PublicConfigurationResolutionReason] {
        lock.withLock { resolutions }
    }
}

private actor TransportConfigurationPersistence: PublicConfigurationPersisting {
    private var readValue: PublicConfigurationPersistenceRead = .empty

    func read() async -> PublicConfigurationPersistenceRead { readValue }

    func write(_ snapshot: PublicConfigurationPersistenceSnapshot) async throws {
        readValue = .stored(snapshot)
    }
}

private struct FixedPublicConfigurationService: PublicConfigurationServicing {
    let resolution: PublicConfigurationResolution

    func resolveCached(now: Date) async -> PublicConfigurationResolution {
        _ = now
        return .conservativeDefault
    }

    func refresh(now: Date) async -> PublicConfigurationResolution {
        _ = now
        return resolution
    }
}

private struct TransportSignedConfigurationFixture {
    let now = Date(timeIntervalSince1970: 1_786_656_000)
    let privateKey: Curve25519.Signing.PrivateKey
    let verifier: PublicConfigurationVerifier

    init() throws {
        let privateKey = Curve25519.Signing.PrivateKey()
        self.privateKey = privateKey
        verifier = PublicConfigurationVerifier(
            policy: PublicConfigurationVerificationPolicy(
                publicKeysByID: ["mb-config-2026-01": privateKey.publicKey.rawRepresentation]
            )
        )
    }

    func envelopeData(version: UInt64, enabled: Bool) throws -> Data {
        let payload = PublicConfigurationPayload(
            schemaVersion: 1,
            configVersion: version,
            issuedAt: now.addingTimeInterval(-60),
            expiresAt: now.addingTimeInterval(3_600),
            presentation: PublicConfigurationPresentation(proValueTriggersEnabled: enabled)
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        encoder.dateEncodingStrategy = .custom { date, encoder in
            var container = encoder.singleValueContainer()
            try container.encode(PublicConfigurationTimestamp.string(from: date))
        }
        let payloadData = try encoder.encode(payload)
        let envelope = SignedPublicConfigurationEnvelope(
            algorithm: "Ed25519",
            keyID: "mb-config-2026-01",
            payloadBase64: payloadData.base64EncodedString(),
            signatureBase64: try privateKey.signature(for: payloadData).base64EncodedString()
        )
        return try encoder.encode(envelope)
    }

    func envelopeDataWithInvalidSignature() throws -> Data {
        let valid = try envelopeData(version: 3, enabled: false)
        var object = try #require(JSONSerialization.jsonObject(with: valid) as? [String: Any])
        let signatureBase64 = try #require(object["signatureBase64"] as? String)
        var signature = try #require(Data(base64Encoded: signatureBase64))
        signature[signature.startIndex] ^= 1
        object["signatureBase64"] = signature.base64EncodedString()
        return try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
    }
}
