import CryptoKit
import Foundation
import Testing
@testable import MindBudget

@Suite(.serialized)
struct PublicConfigurationTransportTests {
    private static let runsLiveDevelopmentWorkerTest =
        ProcessInfo.processInfo.environment["MINDBUDGET_LIVE_PUBLIC_CONFIG_TESTS"] == "1"

    @Test
    func productionSignerGoldenResponseVerifiesWithTheEmbeddedProductionKey() throws {
        // Generated by the independent signer from the repository-external production private
        // key. This is deliberately not produced by the client test fixture encoder.
        let envelope = #"{"algorithm":"Ed25519","keyID":"mb-config-2026-01","payloadBase64":"eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOmZhbHNlfSwic2NoZW1hVmVyc2lvbiI6MX0=","signatureBase64":"LPfUflHQXtEoRWBDXm2KZH2KL0eEUaQQiZW8wn+vI/Lx7Z/5w1RcqvIBRNN7GDO3nr2iVk9tZ4ne6qDbmBw1Dg=="}"#
        let now = try #require(PublicConfigurationTimestamp.date(from: "2026-08-15T03:00:00Z"))
        let verified = try PublicConfigurationVerifier(
            policy: PublicConfigurationProductionTrust.verificationPolicy
        ).verify(envelopeData: Data(envelope.utf8), now: now)

        #expect(verified.payload.configVersion == 1)
        #expect(verified.payload.issuedAt == PublicConfigurationTimestamp.date(from: "2026-08-15T02:00:00Z"))
        #expect(verified.payload.expiresAt == PublicConfigurationTimestamp.date(from: "2026-08-22T02:00:00Z"))
        #expect(verified.payload.presentation.proValueTriggersEnabled == false)
    }

    @Test(.enabled(if: Self.runsLiveDevelopmentWorkerTest))
    func liveDevelopmentWorkerResponsePassesTheProductionTrustAndSchemaBoundary() async throws {
        let result = await FixedPublicConfigurationTransport(environment: .development).fetch(
            metadata: PublicConfigurationRequestMetadata(
                appVersion: "0.9.6",
                lastAcceptedConfigVersion: 1
            )
        )
        guard case let .envelope(data) = result else {
            Issue.record("The live Development Worker did not return an accepted envelope")
            return
        }
        let verified = try PublicConfigurationVerifier(
            policy: PublicConfigurationProductionTrust.verificationPolicy
        ).verify(envelopeData: data, now: Date())

        #expect(verified.payload.configVersion == 1)
        #expect(verified.payload.presentation.proValueTriggersEnabled)
    }

    @Test
    func exactEnvironmentRequestsContainOnlyReviewedMetadataAndNoBody() async throws {
        let expectedHosts: [PublicConfigurationDeploymentEnvironment: String] = [
            .development: "mindbudget-public-config-dev.yehao1105.workers.dev",
            .staging: "mindbudget-public-config-staging.yehao1105.workers.dev",
            .production: "mindbudget-public-config.yehao1105.workers.dev"
        ]

        for environment in PublicConfigurationDeploymentEnvironment.allCases {
            let loader = RecordingPublicConfigurationLoader(
                response: Self.response(url: environment.endpoint),
                data: Data("{}".utf8)
            )
            let transport = FixedPublicConfigurationTransport(
                environment: environment,
                loader: loader
            )

            let result = await transport.fetch(
                metadata: PublicConfigurationRequestMetadata(
                    appVersion: "0.9.6",
                    lastAcceptedConfigVersion: 42
                )
            )
            let request = try #require(await loader.capturedRequest())

            #expect(result == .envelope(Data("{}".utf8)))
            #expect(request.url?.scheme == "https")
            #expect(request.url?.host == expectedHosts[environment])
            #expect(request.url?.path == "/v1/config")
            #expect(request.url?.query == nil)
            #expect(request.httpMethod == "GET")
            #expect(request.httpBody == nil)
            #expect(request.value(forHTTPHeaderField: "Accept") == "application/json")
            #expect(
                request.value(forHTTPHeaderField: FixedPublicConfigurationTransport.appVersionHeader)
                    == "0.9.6"
            )
            #expect(
                request.value(forHTTPHeaderField: FixedPublicConfigurationTransport.configVersionHeader)
                    == "42"
            )
        }
    }

    @Test
    func invalidMetadataFailsBeforeAnyNetworkLoad() async {
        let loader = RecordingPublicConfigurationLoader(
            response: Self.response(url: PublicConfigurationDeploymentEnvironment.production.endpoint),
            data: Data("{}".utf8)
        )
        let transport = FixedPublicConfigurationTransport(
            environment: .production,
            loader: loader
        )

        let invalidVersions = ["", "0.9.6 user", String(repeating: "1", count: 33)]
        for version in invalidVersions {
            #expect(
                await transport.fetch(
                    metadata: PublicConfigurationRequestMetadata(
                        appVersion: version,
                        lastAcceptedConfigVersion: nil
                    )
                ) == PublicConfigurationFetchResult.failed(.invalidRequestMetadata)
            )
        }
        #expect(await loader.loadCount() == 0)
    }

    @Test
    func redirectWrongURLStatusTypeEmptyAndOversizeResponsesFailClosed() async {
        let endpoint = PublicConfigurationDeploymentEnvironment.production.endpoint
        let fixtures: [(HTTPURLResponse, Data, PublicConfigurationTransportFailureReason)] = [
            (Self.response(url: endpoint, status: 302), Data("{}".utf8), .redirectRejected),
            (
                Self.response(url: URL(string: "https://example.invalid/v1/config")!),
                Data("{}".utf8),
                .responseURLMismatch
            ),
            (Self.response(url: endpoint, status: 503), Data("{}".utf8), .invalidHTTPStatus),
            (
                Self.response(url: endpoint, contentType: "text/plain"),
                Data("{}".utf8),
                .invalidContentType
            ),
            (Self.response(url: endpoint), Data(), .emptyResponse),
            (
                Self.response(url: endpoint),
                Data(
                    repeating: 0,
                    count: PublicConfigurationVerificationPolicy.maximumEnvelopeBytes + 1
                ),
                .responseTooLarge
            )
        ]

        for (httpResponse, data, expectedReason) in fixtures {
            let transport = FixedPublicConfigurationTransport(
                environment: .production,
                loader: RecordingPublicConfigurationLoader(response: httpResponse, data: data)
            )
            #expect(
                await transport.fetch(
                    metadata: PublicConfigurationRequestMetadata(
                        appVersion: "0.9.6",
                        lastAcceptedConfigVersion: nil
                    )
                ) == .failed(expectedReason)
            )
        }
    }

    @Test
    func serviceAcceptsVerifiedRemoteAndLogsOnlyClosedReasonCodes() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let persistence = TransportConfigurationPersistence()
        let controller = PublicConfigurationController(
            verifier: fixture.verifier,
            persistence: persistence
        )
        let observer = RecordingPublicConfigurationObserver()
        let fixtureNow = fixture.now
        let service = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(
                result: .envelope(try fixture.envelopeData(version: 3, enabled: true))
            ),
            observer: observer,
            appVersion: "0.9.6",
            nowProvider: { fixtureNow }
        )

        let resolution = try await service.refresh()

        #expect(resolution.source == .remote)
        #expect(resolution.acceptedConfigVersion == 3)
        #expect(resolution.expiresAt == fixture.now.addingTimeInterval(3_600))
        #expect(resolution.presentation.proValueTriggersEnabled)
        #expect(observer.resolutionReasons() == [.remoteAccepted])
        #expect(observer.transportReasons().isEmpty)
    }

    @Test
    func invalidSignatureAndOfflineTransportRetainOnlyVerifiedCache() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let persistence = TransportConfigurationPersistence()
        let controller = PublicConfigurationController(
            verifier: fixture.verifier,
            persistence: persistence
        )
        _ = await controller.acceptRemote(
            envelopeData: try fixture.envelopeData(version: 2, enabled: true),
            now: fixture.now
        )

        let invalidObserver = RecordingPublicConfigurationObserver()
        let fixtureNow = fixture.now
        let invalidService = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(
                result: .envelope(try fixture.envelopeDataWithInvalidSignature())
            ),
            observer: invalidObserver,
            appVersion: "0.9.6",
            nowProvider: { fixtureNow }
        )
        let invalidResolution = try await invalidService.refresh()
        #expect(invalidResolution.source == .verifiedCache)
        #expect(invalidResolution.presentation.proValueTriggersEnabled)
        #expect(invalidObserver.resolutionReasons() == [.rejectedSignature])

        let offlineObserver = RecordingPublicConfigurationObserver()
        let offlineService = PublicConfigurationService(
            controller: controller,
            transport: FixedResultPublicConfigurationTransport(result: .failed(.offline)),
            observer: offlineObserver,
            appVersion: "0.9.6",
            nowProvider: { fixtureNow }
        )
        let offlineResolution = try await offlineService.refresh()
        #expect(offlineResolution.source == .verifiedCache)
        #expect(offlineResolution.presentation.proValueTriggersEnabled)
        #expect(offlineObserver.transportReasons() == [.offline])
        #expect(offlineObserver.resolutionReasons() == [.cacheAccepted])
    }

    @MainActor
    @Test
    func signedPresentationRequiresActionableExactFreeAndExpiresWithoutForegrounding() async throws {
        let controller = try DataController(isStoredInMemoryOnly: true)
        let expirationScheduler = TestPublicConfigurationExpirationScheduler()
        let expiration = Date().addingTimeInterval(3_600)
        let enabled = PublicConfigurationResolution(
            presentation: PublicConfigurationPresentation(proValueTriggersEnabled: true),
            source: .remote,
            acceptedConfigVersion: 1,
            expiresAt: expiration
        )
        let authority = LiveFeatureAccessAuthority()
        let source = TestPublicConfigurationEntitlementSource(
            read: StoreEntitlementRead(
                transactions: [],
                unverifiedCount: 0,
                appEnvironment: .sandbox
            )
        )
        let store = EntitlementStore(
            source: source,
            featureAccessAuthority: authority
        )
        let freeSession = AppSession(
            dataActor: controller.dataActor,
            featureAccessService: authority,
            entitlementStore: store,
            publicConfigurationService: FixedPublicConfigurationService(resolution: enabled),
            publicConfigurationExpirationScheduler: expirationScheduler
        )

        #expect(freeSession.offersAppleOnDeviceAIProValueTrigger == false)
        await freeSession.startCommerceLifecycle()
        #expect(freeSession.commerceSubscriptionAuthorityIsActionable)
        #expect(freeSession.commerceSubscriptionState == .none)
        await freeSession.refreshPublicConfiguration()
        #expect(freeSession.offersAppleOnDeviceAIProValueTrigger)
        await expirationScheduler.waitUntilScheduled()
        await expirationScheduler.expire()
        #expect(await eventually { !freeSession.offersAppleOnDeviceAIProValueTrigger })
        await store.stop()
    }

    @MainActor
    @Test
    func unavailableUnverifiedAndFailedPaidAuthorityNeverExposeTheFreeValueTrigger() async throws {
        let controller = try DataController(isStoredInMemoryOnly: true)
        let enabled = PublicConfigurationResolution(
            presentation: PublicConfigurationPresentation(proValueTriggersEnabled: true),
            source: .remote,
            acceptedConfigVersion: 1,
            expiresAt: Date().addingTimeInterval(3_600)
        )

        for read in [
            StoreEntitlementRead(
                transactions: [],
                unverifiedCount: 0,
                isComplete: false,
                appEnvironment: .sandbox
            ),
            StoreEntitlementRead(
                transactions: [],
                unverifiedCount: 1,
                appEnvironment: .sandbox
            )
        ] {
            let authority = LiveFeatureAccessAuthority()
            let source = TestPublicConfigurationEntitlementSource(read: read)
            let store = EntitlementStore(source: source, featureAccessAuthority: authority)
            let session = AppSession(
                dataActor: controller.dataActor,
                featureAccessService: authority,
                entitlementStore: store,
                publicConfigurationService: FixedPublicConfigurationService(resolution: enabled)
            )
            await session.startCommerceLifecycle()
            await session.refreshPublicConfiguration()
            #expect(session.commerceSubscriptionState == .unavailable)
            #expect(session.commerceSubscriptionAuthorityIsActionable == false)
            #expect(session.offersAppleOnDeviceAIProValueTrigger == false)
            await store.stop()
        }

        let paidAuthority = LiveFeatureAccessAuthority()
        let paidSource = TestPublicConfigurationEntitlementSource(read: Self.paidRead())
        let paidStore = EntitlementStore(
            source: paidSource,
            featureAccessAuthority: paidAuthority
        )
        let paidSession = AppSession(
            dataActor: controller.dataActor,
            featureAccessService: paidAuthority,
            entitlementStore: paidStore,
            publicConfigurationService: FixedPublicConfigurationService(resolution: enabled)
        )
        await paidSession.startCommerceLifecycle()
        await paidSession.refreshPublicConfiguration()
        #expect(paidSession.existingPremiumEntryAccess.offersAppleOnDeviceAI)
        #expect(paidSession.offersAppleOnDeviceAIProValueTrigger == false)

        await paidSource.setRead(
            StoreEntitlementRead(
                transactions: [],
                unverifiedCount: 0,
                isComplete: false,
                appEnvironment: .sandbox
            )
        )
        await paidSession.refreshCommerceEntitlements()
        #expect(paidSession.existingPremiumEntryAccess.offersAppleOnDeviceAI == false)
        #expect(paidSession.commerceSubscriptionState == .unavailable)
        #expect(paidSession.commerceSubscriptionAuthorityIsActionable == false)
        #expect(paidSession.offersAppleOnDeviceAIProValueTrigger == false)
        await paidStore.stop()
    }

    @Test
    func responseExpiringWhileTheRequestIsSuspendedIsNeverAccepted() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let clock = TestPublicConfigurationClock(now: fixture.now)
        let gate = PublicConfigurationTestGate()
        let transport = GatedPublicConfigurationTransport(
            result: .envelope(
                try fixture.envelopeData(
                    version: 1,
                    enabled: true,
                    expiresAt: fixture.now.addingTimeInterval(30)
                )
            ),
            gate: gate
        )
        let persistence = TransportConfigurationPersistence()
        let observer = RecordingPublicConfigurationObserver()
        let service = PublicConfigurationService(
            controller: PublicConfigurationController(
                verifier: fixture.verifier,
                persistence: persistence
            ),
            transport: transport,
            observer: observer,
            appVersion: "0.9.6",
            nowProvider: { clock.now() }
        )

        let refresh = Task { try await service.refresh() }
        await gate.waitUntilEntered()
        clock.set(fixture.now.addingTimeInterval(30))
        await gate.release()
        let resolution = try await refresh.value

        #expect(resolution == .conservativeDefault)
        #expect(observer.resolutionReasons() == [.rejectedExpired])
        #expect(await persistence.writeCount() == 0)
    }

    @Test
    func cancellingRefreshCancelsTheNetworkOperationAndPreventsAcceptance() async throws {
        let fixture = try TransportSignedConfigurationFixture()
        let transport = CancellationRecordingPublicConfigurationTransport(
            envelope: try fixture.envelopeData(version: 1, enabled: true)
        )
        let persistence = TransportConfigurationPersistence()
        let fixtureNow = fixture.now
        let service = PublicConfigurationService(
            controller: PublicConfigurationController(
                verifier: fixture.verifier,
                persistence: persistence
            ),
            transport: transport,
            observer: RecordingPublicConfigurationObserver(),
            appVersion: "0.9.6",
            nowProvider: { fixtureNow }
        )

        let refresh = Task { try await service.refresh() }
        await transport.waitUntilStarted()
        refresh.cancel()

        do {
            _ = try await refresh.value
            Issue.record("A canceled refresh unexpectedly returned a presentation")
        } catch is CancellationError {
            // Expected: no canceled result reaches AppSession.
        } catch {
            Issue.record("Unexpected cancellation error: \(error)")
        }
        #expect(await transport.wasCancelled())
        #expect(await persistence.writeCount() == 0)
    }

    private static func paidRead() -> StoreEntitlementRead {
        StoreEntitlementRead(
            transactions: [
                VerifiedStoreTransaction(
                    transactionID: 42,
                    productID: StoreProductID.proMonthly.rawValue,
                    environment: .sandbox,
                    isPurchased: true,
                    isRevoked: false,
                    expirationDate: Date().addingTimeInterval(3_600),
                    subscriptionState: .subscribed,
                    hasVerifiedStatusTransaction: true,
                    hasVerifiedRenewalInfo: true,
                    hasVerifiedAppBundle: true
                )
            ],
            unverifiedCount: 0,
            appEnvironment: .sandbox
        )
    }

    private static func response(
        url: URL,
        status: Int = 200,
        contentType: String = "application/json; charset=utf-8"
    ) -> HTTPURLResponse {
        HTTPURLResponse(
            url: url,
            statusCode: status,
            httpVersion: "HTTP/1.1",
            headerFields: ["Content-Type": contentType]
        )!
    }
}

private actor RecordingPublicConfigurationLoader: PublicConfigurationHTTPLoading {
    private let response: HTTPURLResponse
    private let data: Data
    private var requests: [URLRequest] = []

    init(response: HTTPURLResponse, data: Data) {
        self.response = response
        self.data = data
    }

    func load(
        request: URLRequest,
        maximumResponseBytes: Int
    ) async throws -> PublicConfigurationHTTPResponse {
        _ = maximumResponseBytes
        requests.append(request)
        return PublicConfigurationHTTPResponse(data: data, response: response)
    }

    func capturedRequest() -> URLRequest? { requests.last }
    func loadCount() -> Int { requests.count }
}

private struct FixedResultPublicConfigurationTransport: PublicConfigurationFetching {
    let result: PublicConfigurationFetchResult

    func fetch(metadata: PublicConfigurationRequestMetadata) async -> PublicConfigurationFetchResult {
        _ = metadata
        return result
    }
}

private final class RecordingPublicConfigurationObserver: PublicConfigurationReasonObserving,
    @unchecked Sendable {
    private let lock = NSLock()
    private var transports: [PublicConfigurationTransportFailureReason] = []
    private var resolutions: [PublicConfigurationResolutionReason] = []

    func record(transport reason: PublicConfigurationTransportFailureReason) {
        lock.withLock { transports.append(reason) }
    }

    func record(resolution reason: PublicConfigurationResolutionReason) {
        lock.withLock { resolutions.append(reason) }
    }

    func transportReasons() -> [PublicConfigurationTransportFailureReason] {
        lock.withLock { transports }
    }

    func resolutionReasons() -> [PublicConfigurationResolutionReason] {
        lock.withLock { resolutions }
    }
}

private actor TransportConfigurationPersistence: PublicConfigurationPersisting {
    private var readValue: PublicConfigurationPersistenceRead = .empty
    private var writes = 0

    func read() async -> PublicConfigurationPersistenceRead { readValue }

    func write(_ snapshot: PublicConfigurationPersistenceSnapshot) async throws {
        writes += 1
        readValue = .stored(snapshot)
    }

    func writeCount() -> Int { writes }
}

private struct FixedPublicConfigurationService: PublicConfigurationServicing {
    let resolution: PublicConfigurationResolution

    func resolveCached(now: Date) async -> PublicConfigurationResolution {
        _ = now
        return .conservativeDefault
    }

    func refresh() async throws -> PublicConfigurationResolution {
        return resolution
    }
}

private struct TransportSignedConfigurationFixture {
    let now = Date(timeIntervalSince1970: 1_786_656_000)
    let privateKey: Curve25519.Signing.PrivateKey
    let verifier: PublicConfigurationVerifier

    init() throws {
        let privateKey = Curve25519.Signing.PrivateKey()
        self.privateKey = privateKey
        verifier = PublicConfigurationVerifier(
            policy: PublicConfigurationVerificationPolicy(
                publicKeysByID: ["mb-config-2026-01": privateKey.publicKey.rawRepresentation]
            )
        )
    }

    func envelopeData(
        version: UInt64,
        enabled: Bool,
        expiresAt: Date? = nil
    ) throws -> Data {
        let payload = PublicConfigurationPayload(
            schemaVersion: 1,
            configVersion: version,
            issuedAt: now.addingTimeInterval(-60),
            expiresAt: expiresAt ?? now.addingTimeInterval(3_600),
            presentation: PublicConfigurationPresentation(proValueTriggersEnabled: enabled)
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        encoder.dateEncodingStrategy = .custom { date, encoder in
            var container = encoder.singleValueContainer()
            try container.encode(PublicConfigurationTimestamp.string(from: date))
        }
        let payloadData = try encoder.encode(payload)
        let envelope = SignedPublicConfigurationEnvelope(
            algorithm: "Ed25519",
            keyID: "mb-config-2026-01",
            payloadBase64: payloadData.base64EncodedString(),
            signatureBase64: try privateKey.signature(for: payloadData).base64EncodedString()
        )
        return try encoder.encode(envelope)
    }

    func envelopeDataWithInvalidSignature() throws -> Data {
        let valid = try envelopeData(version: 3, enabled: false)
        var object = try #require(JSONSerialization.jsonObject(with: valid) as? [String: Any])
        let signatureBase64 = try #require(object["signatureBase64"] as? String)
        var signature = try #require(Data(base64Encoded: signatureBase64))
        signature[signature.startIndex] ^= 1
        object["signatureBase64"] = signature.base64EncodedString()
        return try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
    }
}

private final class TestPublicConfigurationClock: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Date

    init(now: Date) {
        value = now
    }

    func now() -> Date {
        lock.withLock { value }
    }

    func set(_ now: Date) {
        lock.withLock { value = now }
    }
}

private actor PublicConfigurationTestGate {
    private var entered = false
    private var released = false
    private var entryWaiters: [CheckedContinuation<Void, Never>] = []
    private var releaseWaiters: [CheckedContinuation<Void, Never>] = []

    func enterAndWait() async {
        entered = true
        entryWaiters.forEach { $0.resume() }
        entryWaiters.removeAll()
        guard !released else { return }
        await withCheckedContinuation { continuation in
            releaseWaiters.append(continuation)
        }
    }

    func waitUntilEntered() async {
        guard !entered else { return }
        await withCheckedContinuation { continuation in
            entryWaiters.append(continuation)
        }
    }

    func release() {
        released = true
        releaseWaiters.forEach { $0.resume() }
        releaseWaiters.removeAll()
    }
}

private struct GatedPublicConfigurationTransport: PublicConfigurationFetching {
    let result: PublicConfigurationFetchResult
    let gate: PublicConfigurationTestGate

    func fetch(metadata: PublicConfigurationRequestMetadata) async -> PublicConfigurationFetchResult {
        _ = metadata
        await gate.enterAndWait()
        return result
    }
}

private actor CancellationRecordingPublicConfigurationTransport: PublicConfigurationFetching {
    private let envelope: Data
    private var started = false
    private var cancelled = false
    private var startWaiters: [CheckedContinuation<Void, Never>] = []

    init(envelope: Data) {
        self.envelope = envelope
    }

    func fetch(metadata: PublicConfigurationRequestMetadata) async -> PublicConfigurationFetchResult {
        _ = metadata
        started = true
        startWaiters.forEach { $0.resume() }
        startWaiters.removeAll()
        do {
            try await Task.sleep(for: .seconds(60))
            return .envelope(envelope)
        } catch {
            cancelled = true
            return .failed(.cancelled)
        }
    }

    func waitUntilStarted() async {
        guard !started else { return }
        await withCheckedContinuation { continuation in
            startWaiters.append(continuation)
        }
    }

    func wasCancelled() -> Bool { cancelled }
}

private actor TestPublicConfigurationExpirationScheduler: PublicConfigurationExpirationScheduling {
    private let gate = PublicConfigurationTestGate()

    func wait(until expiration: Date) async throws {
        _ = expiration
        await gate.enterAndWait()
        try Task.checkCancellation()
    }

    func waitUntilScheduled() async {
        await gate.waitUntilEntered()
    }

    func expire() async {
        await gate.release()
    }
}

private final class TestPublicConfigurationUpdateChannel: @unchecked Sendable {
    let stream: AsyncStream<StoreTransactionSignal>
    let continuation: AsyncStream<StoreTransactionSignal>.Continuation

    init() {
        var captured: AsyncStream<StoreTransactionSignal>.Continuation?
        stream = AsyncStream { captured = $0 }
        continuation = captured!
    }
}

private struct TestPublicConfigurationEntitlementSource: StoreEntitlementSourcing {
    private let state: TestPublicConfigurationEntitlementState
    private let channel = TestPublicConfigurationUpdateChannel()

    init(read: StoreEntitlementRead) {
        state = TestPublicConfigurationEntitlementState(read: read)
    }

    func currentAppEnvironment() async -> StoreRuntimeEnvironment? {
        await state.read().appEnvironment
    }

    func currentEntitlements() async -> StoreEntitlementRead {
        await state.read()
    }

    func unfinishedTransactions() async -> StoreUnfinishedTransactionRead {
        StoreUnfinishedTransactionRead(transactions: [], unverifiedCount: 0)
    }

    func listenForUpdates(
        _ handler: @Sendable @escaping (StoreTransactionSignal) async -> Void
    ) async {
        for await signal in channel.stream {
            guard !Task.isCancelled else { return }
            await handler(signal)
        }
    }

    @MainActor
    func purchase(_ productID: StoreProductID) async throws -> StorePurchaseResult {
        _ = productID
        return .userCancelled
    }

    func synchronizePurchases() async throws {}

    func setRead(_ read: StoreEntitlementRead) async {
        await state.set(read)
    }
}

private actor TestPublicConfigurationEntitlementState {
    private var value: StoreEntitlementRead

    init(read: StoreEntitlementRead) {
        value = read
    }

    func read() -> StoreEntitlementRead { value }
    func set(_ read: StoreEntitlementRead) { value = read }
}

@MainActor
private func eventually(
    timeout: Duration = .seconds(2),
    condition: @MainActor () -> Bool
) async -> Bool {
    let clock = ContinuousClock()
    let deadline = clock.now.advanced(by: timeout)
    while clock.now < deadline {
        if condition() { return true }
        do {
            try await clock.sleep(for: .milliseconds(10))
        } catch {
            return false
        }
    }
    return condition()
}
