/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b7185c9b32e699262549266f888d4e29)
interface __BaseEnv_Env {
	TELEMETRY_DB: D1Database;
	TELEMETRY_EDGE_RATE_LIMITER: RateLimit;
	TELEMETRY_IDENTITY_RATE_LIMITER: RateLimit;
	DEPLOYMENT_ENVIRONMENT: "development" | "staging" | "production";
	EXPECTED_HOST: "mindbudget-telemetry-dev.yehao1105.workers.dev" | "mindbudget-telemetry-staging.yehao1105.workers.dev" | "mindbudget-telemetry.yehao1105.workers.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		TELEMETRY_DB: D1Database;
		TELEMETRY_EDGE_RATE_LIMITER: RateLimit;
		TELEMETRY_IDENTITY_RATE_LIMITER: RateLimit;
		DEPLOYMENT_ENVIRONMENT: "development";
		EXPECTED_HOST: "mindbudget-telemetry-dev.yehao1105.workers.dev";
	}
	interface StagingEnv {
		TELEMETRY_DB: D1Database;
		TELEMETRY_EDGE_RATE_LIMITER: RateLimit;
		TELEMETRY_IDENTITY_RATE_LIMITER: RateLimit;
		DEPLOYMENT_ENVIRONMENT: "staging";
		EXPECTED_HOST: "mindbudget-telemetry-staging.yehao1105.workers.dev";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENVIRONMENT" | "EXPECTED_HOST">> {}
}
