/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 95d8dbbac5697ca0ab0191681607203d)
interface __BaseEnv_Env {
	PUBLIC_CONFIG_RATE_LIMITER: RateLimit;
	DEPLOYMENT_ENVIRONMENT: "development" | "staging" | "production";
	EXPECTED_HOST: "mindbudget-public-config-dev.yehao1105.workers.dev" | "mindbudget-public-config-staging.yehao1105.workers.dev" | "mindbudget-public-config.yehao1105.workers.dev";
	PUBLIC_CONFIG_PAYLOAD_BASE64: "eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOnRydWV9LCJzY2hlbWFWZXJzaW9uIjoxfQ==" | "eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOmZhbHNlfSwic2NoZW1hVmVyc2lvbiI6MX0=";
	PUBLIC_CONFIG_SIGNATURE_BASE64: "JsYasCC7FClzyjYT42PNUNeSt1w43hOP8b9I28UDugaKlpNmhmvofSctxyol+4qhEMey7+Aidx/r0kjxJrV3CA==" | "LPfUflHQXtEoRWBDXm2KZH2KL0eEUaQQiZW8wn+vI/Lx7Z/5w1RcqvIBRNN7GDO3nr2iVk9tZ4ne6qDbmBw1Dg==";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevelopmentEnv {
		PUBLIC_CONFIG_RATE_LIMITER: RateLimit;
		DEPLOYMENT_ENVIRONMENT: "development";
		EXPECTED_HOST: "mindbudget-public-config-dev.yehao1105.workers.dev";
		PUBLIC_CONFIG_PAYLOAD_BASE64: "eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOnRydWV9LCJzY2hlbWFWZXJzaW9uIjoxfQ==";
		PUBLIC_CONFIG_SIGNATURE_BASE64: "JsYasCC7FClzyjYT42PNUNeSt1w43hOP8b9I28UDugaKlpNmhmvofSctxyol+4qhEMey7+Aidx/r0kjxJrV3CA==";
	}
	interface StagingEnv {
		PUBLIC_CONFIG_RATE_LIMITER: RateLimit;
		DEPLOYMENT_ENVIRONMENT: "staging";
		EXPECTED_HOST: "mindbudget-public-config-staging.yehao1105.workers.dev";
		PUBLIC_CONFIG_PAYLOAD_BASE64: "eyJjb25maWdWZXJzaW9uIjoxLCJleHBpcmVzQXQiOiIyMDI2LTA4LTIyVDAyOjAwOjAwWiIsImlzc3VlZEF0IjoiMjAyNi0wOC0xNVQwMjowMDowMFoiLCJwcmVzZW50YXRpb24iOnsicHJvVmFsdWVUcmlnZ2Vyc0VuYWJsZWQiOnRydWV9LCJzY2hlbWFWZXJzaW9uIjoxfQ==";
		PUBLIC_CONFIG_SIGNATURE_BASE64: "JsYasCC7FClzyjYT42PNUNeSt1w43hOP8b9I28UDugaKlpNmhmvofSctxyol+4qhEMey7+Aidx/r0kjxJrV3CA==";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENVIRONMENT" | "EXPECTED_HOST" | "PUBLIC_CONFIG_PAYLOAD_BASE64" | "PUBLIC_CONFIG_SIGNATURE_BASE64">> {}
}
